[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure Prisma generated files are included
[functions]
  included_files = ["lib/generated/**"]

# Handle Next.js routing
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Handle static files
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

# Handle all other routes (SPA fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 